# VAULT KEYS REMOVED

mc_admin: sysadmin
mc_pwd: !vault |
  $ANSIBLE_VAULT;1.1;AES256

dd_pwd: !vault |
  $ANSIBLE_VAULT;1.1;AES256

boost_user: boostuser
boost_pwd: !vault |
  $ANSIBLE_VAULT;1.1;AES256