---
- name: "PowerProtect DDMC credentials demo"
  hosts: localhost
  collections:
    - community.general
  become: no
  gather_facts: false

  vars:
  vars_files:
    - vars/environment.yaml
    - vars/credentials.yaml
  tasks:

# WAIT FOR HTTPS RESPONSE FROM POWERPROTECT DATA DOMAIN  
  - name: "( {{mc_host}} ): Waiting for HTTPS connectivity."
    wait_for:
      host: "{{mc_host}}"
      port: 443
      state: started
      delay: 1
      sleep: 60
      timeout: 600
    register: waitforddmc

# AUTHENTICATE TO DDMC REST API
  - name: "( {{mc_host}} ): Authenticate to PowerProtect DDMC REST API"
    uri:
      url: https://{{mc_host}}:3009/rest/v1.0/auth
      method: POST
      force_basic_auth: no
      validate_certs: no
      return_content: yes
      body_format: json
      body: |
        {
          "username": "{{mc_admin}}",
          "password": "{{mc_pwd}}"
        }
      status_code: 201
    register: mc_token1

  - name:
    debug:
      var:  mc_token1.x_dd_auth_token

# QUERY FOR ATTACHED DDVE SYSTEMS
  - name: "( {{mc_host}} ): Adding {{dd_host_1}} to system configuration"
    uri:
      url: https://{{mc_host}}:3009/rest/v2.0/dd-systems
      method: GET
      headers:
        X-DD-AUTH-TOKEN: "{{mc_token1.x_dd_auth_token}}"
        Content-Type: "application/json"
      force_basic_auth: no
      validate_certs: no
      return_content: yes
      body_format: json
      status_code: 200
    register: get_dd_systems

  - name:
    debug:
      var:  get_dd_systems.json.system_info

# CREATE THE DDBOOST USER
  - name: "( {{mc_host}} ): Create the boost user"
    uri:
      url: https://{{mc_host}}:3009/rest/v1.0/dd-systems/{{item.id}}/users
      method: POST
      headers:
        X-DD-AUTH-TOKEN: "{{mc_token1.x_dd_auth_token}}"
        Content-Type: "application/json"
      force_basic_auth: no
      validate_certs: no
      body_format: json
      body: |
        {
          "name": "{{boost_user}}",
          "role": "none",
          "password":"{{boost_pwd}}"
        }
      return_content: yes
      status_code: 201
    loop: "{{get_dd_systems.json.system_info}}"
    register: create_user

# ASSIGN BOOST ACCESS
  - name: "( {{mc_host}} ): Assign user boost access"
    uri:
      url: https://{{mc_host}}:3009/rest/v1.0/dd-systems/{{item.id}}/protocols/ddboost/users
      method: PUT
      headers:
        X-DD-AUTH-TOKEN: "{{mc_token1.x_dd_auth_token}}"
        Content-Type: "application/json"
      force_basic_auth: no
      validate_certs: no
      body_format: json
      body: |
        {
          "user": "{{boost_user}}",
          "operation": "assign"
        }
      return_content: yes
      status_code: 200
    loop: "{{get_dd_systems.json.system_info}}"
    register: assign_user